-- liquibase formatted sql

-- changeset sgots:1
CREATE TABLE notifications (
    id          INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     INT8 NOT NULL,
    target_time TIMESTAMP NOT NULL CHECK (target_time > CURRENT_TIMESTAMP),
    message     VARCHAR(255)
)